WebAPIDiff/Areas/HelpPage/Controllers/HelpController.cs
using System;
using System.Web.Http;
using System.Web.Mvc;
using WebAPIDiff.Areas.HelpPage.ModelDescriptions;
using WebAPIDiff.Areas.HelpPage.Models;

namespace WebAPIDiff.Areas.HelpPage.Controllers
{
    /// <summary>
    /// The controller that will handle requests for the help page.
    /// </summary>
    public class HelpController : Controller
    {
        private const string ErrorViewName = "Error";

        public HelpController()
            : this(GlobalConfiguration.Configuration)
        {
        }

        public HelpController(HttpConfiguration config)
        {
            Configuration = config;
        }

        public HttpConfiguration Configuration { get; private set; }

        public ActionResult Index()
        {
            ViewBag.DocumentationProvider = Configuration.Services.GetDocumentationProvider();
            return View(Configuration.Services.GetApiExplorer().ApiDescriptions);
        }

        public ActionResult Api(string apiId)
        {
            if (!String.IsNullOrEmpty(apiId))
            {
                HelpPageApiModel apiModel = Configuration.GetHelpPageApiModel(apiId);
                if (apiModel != null)
                {
                    return View(apiModel);
                }
            }

            return View(ErrorViewName);
        }

        public ActionResult ResourceModel(string modelName)
        {
            if (!String.IsNullOrEmpty(modelName))
            {
                ModelDescriptionGenerator modelDescriptionGenerator = Configuration.GetModelDescriptionGenerator();
                ModelDescription modelDescription;
                if (modelDescriptionGenerator.GeneratedModels.TryGetValue(modelName, out modelDescription))
                {
                    return View(modelDescription);
                }
            }

            return View(ErrorViewName);
        }
    }
}

WebAPIDiff/Controllers/DiffMvcController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebAPIDiff.Domain.Abstract;
using WebAPIDiff.Domain.Services;

namespace WebAPIDiff.Controllers
{
  public class DiffMvcController : Controller
  {
    private IDiffRepository _diffRepository;

    public DiffMvcController(IDiffRepository diffRepository)
    {
      if (diffRepository == null) throw new ArgumentNullException(nameof(diffRepository));

      _diffRepository = diffRepository;
    }

    #region Queries and Lists

    [HttpGet]
    // GET: DiffMvc
    public ActionResult List() {
      var diffService = new DiffService(_diffRepository);

      var diffList = diffService.GetDiffs().ToList();

      //_diffRepository.GetDiffs().ToList()
      return View(diffList);
    }

    #endregion

  }
}

WebAPIDiff/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>@ViewBag.Title</title>
  <link href="~/Content/Site.css" rel="stylesheet" type="text/css"/>
  <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css"/>
  <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
  <div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        @Html.ActionLink("Resolving differences", "List", "DiffMvc", new {area = ""}, new {@class = "navbar-brand"})
      </div>
      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <li>@Html.ActionLink("Diff List", "List", "DiffMvc", new {area = ""}, null)</li>
          <li>@Html.ActionLink("API", "Index", "Help", new {area = "HelpPage" }, null)</li>
        </ul>
      </div>
    </div>
  </div>

  <div class="container body-content">
    @RenderBody()
    <hr />
  </div>

  <script src="~/Scripts/jquery-2.2.4.min.js"></script>
  <script src="~/Scripts/bootstrap.min.js"></script>
  @RenderSection("scripts", required: false)
</body>
</html>